config/routes.rb
Rails.application.routes.draw do
  root "messages#index"
  resources :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.order(created_at: :desc).all
  end

  def show
    @message = Message.find(params[:id])
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    if @message.save
      flash[:info] = "You have successfully posted a new message!"
      redirect_to messages_path
    else
      render 'new'
    end
  end

  private
    def message_params
      params.require(:message).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessengerApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Bungee" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <header>
        <h3 id="app_logo"><%= link_to "Messenger App", root_url %></h3>
      </header>

      <div class="main">
        <%= yield %>
      </div>

      <section class="left-side">

      </section>

      <section class="right-side">

      </section>

      <footer>
        <p>Created By: Nolan Frazier</p>
      </footer>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for @message do |f| %>
  <%= f.text_area :content, :autofocus => true %>
  <%= f.submit "Post", class: "btn" %>
<% end %>

app/views/messages/index.html.erb
<%= link_to "New message", new_message_path, class: "btn btn-home" %>

<div class="messages">
  <% @messages.each do |message| %>
    <div class="message">
      <p><%= message.content %></p>
      <p class="time"><%= time_ago_in_words(message.created_at) %></p>
    </div>
  <% end %>
</div>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render "form" %>

app/views/messages/show.html.erb
<h1>Message</h1>
<p><%= @message.content %></p>
<p><%= @message.created_at %></p>